### ISSUE TITLE
Muito interessante o Gerador de Probabilidade de Numeros Sorteados (Mega-Sena ou LotoFacil)

### ISSUE THREAD

**Issue by venelouis** [Carlos-CGS/ProjetosPython#1]
Uma pergunta já deu uma testada e já fez algumas apostas? rs Muito legal. Parabéns pelo repositório.

**Comment by Carlos-CGS** [comment]
Vou testar essa semana fazendo algumas apostas. rsrs. Obg pelo feedback.

Em sex., 15 de mar. de 2024 às 19:57, @venelouis ***@***.***>
escreveu:
